apiVersion: v1
kind: Service
metadata:
  name: mysql-db
  namespace: default
spec:
  type: NodePort
  selector:
    app: mysql-app
  ports: 
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30036
